pull_request_rules:
  - name: Merge Guillaume's pull requests
    conditions:
      - "author=GuillaumeOj"
      - "label!=work-in-progress"
      - "label!=manual merge"
      - "check-success=pep8"
      - "check-success=test"
      - "check-success=coverage"
    actions:
      merge:
        strict: "smart"
        method: "rebase"
      delete_head_branch:
        force: True
  - name: automatic merge from dependabot
    conditions:
      - author=dependabot[bot]
      - label!=work-in-progress
      - label!=manual merge
      - "check-success=pep8"
      - "check-success=test"
      - "check-success=coverage"
    actions:
      merge:
        strict: "smart"
        method: rebase
      delete_head_branch:
        force: True  
  - name: request review
    conditions:
      - -author=dependabot[bot]
      - label!=work-in-progress
      - label!=no-review-needed
      - -closed
    actions:
      request_reviews:
        users:
          - guillaumeoj
