pull_request_rules:
  - name: Merge Guillaume's pull requests
    conditions:
      - "author=GuillaumeOj"
      - "check-success=pep8"
      - "check-success=test"
      - "check-success=coverage"
    actions:
      merge:
        strict: "smart"
        method: squash
      delete_head_branch:
        force: True
  - name: Merge Dependabot's pull requests
    conditions:
      - "author=dependabot-preview[bot]"
      - "check-success=pep8"
      - "check-success=test"
      - "check-success=coverage"
    actions:
      merge:
        strict: "smart"
        method: squash 
