pull_request_rules:
  - name: Merge Guillaume's pull requests
    conditions:
      - author=GuillaumeOj
      - check-success=pep8
      - check-success=test
      - check-success=coverage
      - check-success~=^security/snyk
    actions:
      merge:
        strict: smart
        method: rebase 
      delete_head_branch:
        force: True
  - name: Merge Snyk's pull requests
    conditions:
      - title~=^\[Snyk\]
      - head~=^snyk-fix
      - check-success=pep8
      - check-success=test
      - check-success=coverage
      - check-success~=^security/snyk
    actions:
      merge:
        strict: smart
        method: rebase 
