pull_request_rules:
  - name: Merge Guillaume's pull requests
    conditions:
      - "author=GuillaumeOj"
      - "label!=work-in-progress"
      - "label!=manual merge"
      - "status-success=Travis CI - Branch"
      - "status-success=Travis CI - Pull Request"
    actions:
      merge:
        strict: "smart"
        method: "rebase"
      delete_head_branch:
        force: True
