language: python
python:
  - '3.8'

env: DJANGO_SETTINGS_MODULE="config.settings.travis"

services:
  - postgresql

before_install:
  - pip install -U pip
  - pip --version

install:
  - pip install -r requirements.txt

script:
  - python3 manage.py test
  - black . --check
  - isort . --check
