# Generated by Django 3.0.7 on 2020-08-01 11:30

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0002_experience_pathway"),
    ]

    operations = [
        migrations.AlterField(
            model_name="about",
            name="social_links",
            field=models.ManyToManyField(blank=True, to="resume.Social"),
        ),
        migrations.AlterField(
            model_name="pathway",
            name="expriences",
            field=models.ManyToManyField(blank=True, to="resume.Experience"),
        ),
    ]
