# Generated by Django 3.0.7 on 2020-08-01 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_auto_20200801_1330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pathway',
            old_name='expriences',
            new_name='experiences',
        ),
    ]
