# Generated by Django 3.0.7 on 2020-08-01 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_auto_20200801_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pathway',
            name='experiences',
            field=models.ManyToManyField(to='resume.Experience'),
        ),
    ]
