# Generated by Django 3.0.7 on 2020-08-01 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_auto_20200801_1811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pathway',
            name='experiences',
        ),
        migrations.AddField(
            model_name='experience',
            name='pathway',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='resume.PathWay'),
            preserve_default=False,
        ),
    ]
