# Generated by Django 3.0.7 on 2020-08-01 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_auto_20200801_1818'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience',
            old_name='pathway',
            new_name='path',
        ),
    ]
