# Generated by Django 3.0.7 on 2020-08-02 09:20

from django.db import migrations
from django.db import models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0007_auto_20200801_1820"),
    ]

    operations = [
        migrations.AddField(
            model_name="pathway",
            name="about",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="resume.About",
            ),
            preserve_default=False,
        ),
    ]
