# Generated by Django 3.0.7 on 2020-08-02 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0008_pathway_about'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='social_links',
        ),
        migrations.AddField(
            model_name='social',
            name='about',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='resume.About'),
            preserve_default=False,
        ),
    ]
