# Generated by Django 3.0.7 on 2020-08-02 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0009_auto_20200802_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social',
            name='about',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_about', to='resume.About'),
        ),
    ]
