# Generated by Django 3.0.7 on 2020-08-02 11:31

from django.db import migrations
from django.db import models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0010_auto_20200802_1320"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pathway",
            name="about",
        ),
        migrations.AddField(
            model_name="about",
            name="paths",
            field=models.ManyToManyField(to="resume.PathWay"),
        ),
        migrations.AddField(
            model_name="experience",
            name="about",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="resume.About"
            ),
            preserve_default=False,
        ),
    ]
