# Generated by Django 3.0.7 on 2020-08-02 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0012_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='about',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='resume.About'),
        ),
    ]
