# Generated by Django 3.0.7 on 2020-08-02 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0013_auto_20200802_1347'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='achieve',
            new_name='achieved',
        ),
    ]
