# Generated by Django 3.0.7 on 2020-08-02 12:05

import django.core.validators
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0014_auto_20200802_1402"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="number",
            field=models.IntegerField(
                default=1, validators=[django.core.validators.MinLengthValidator(1)]
            ),
            preserve_default=False,
        ),
    ]
