# Generated by Django 3.0.7 on 2020-08-02 12:07

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0015_project_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="number",
            field=models.IntegerField(),
        ),
    ]
