# Generated by Django 3.1.1 on 2020-10-11 19:10

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0019_auto_20201011_2025"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="pending",
            field=models.BooleanField(default=False),
        ),
    ]
