# Generated by Django 3.1.3 on 2021-01-16 18:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0021_auto_20201011_2111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='paths',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='about',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='path',
        ),
        migrations.RemoveField(
            model_name='project',
            name='about',
        ),
        migrations.RemoveField(
            model_name='social',
            name='about',
        ),
        migrations.AddField(
            model_name='experience',
            name='experience_type',
            field=models.CharField(choices=[('PRO', 'Profesionnal'), ('EDU', 'Education')], default='PRO', max_length=3),
        ),
        migrations.AlterField(
            model_name='about',
            name='country',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='about',
            name='first_name',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='about',
            name='last_name',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='about',
            name='place',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='experience',
            name='subtitle',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
        migrations.AlterField(
            model_name='experience',
            name='title',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
        migrations.AlterField(
            model_name='social',
            name='icon',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
        migrations.AlterField(
            model_name='social',
            name='title',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='social',
            name='url',
            field=models.URLField(validators=[django.core.validators.URLValidator]),
        ),
        migrations.DeleteModel(
            name='PathWay',
        ),
    ]
