# Generated by Django 3.1.7 on 2021-03-07 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0024_auto_20210307_1812'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Experience',
        ),
    ]
