# Generated by Django 3.1.7 on 2021-03-07 21:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0025_delete_experience'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolio',
            options={'ordering': ['-publishing_date']},
        ),
        migrations.AddField(
            model_name='portfolio',
            name='publishing_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
