# This workflow will install Python dependencies, run pep8 and tests

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  pep8:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install Tox
      run: |
        python -m pip install --upgrade pip
        pip install tox
    - name: Run pep8
      run: |
        tox -e pep8
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install Tox
      run: |
        python -m pip install --upgrade pip
        pip install tox
    - name: Run tests
      run: |
        tox -e py39
  coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install Tox
      run: |
        python -m pip install --upgrade pip
        pip install tox
    - name: Run coverage
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      run: |
        tox -e coverage
